name: asan_gcc_13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcc:13

    steps:
    - uses: actions/checkout@v3

    - name: Install CMake
      run: |
          apt update -y
          apt install -y cmake
          apt install -y python3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7.1'

    - name: Print python version
      run: python --version

    - name: Add safe repo directory
      run: git config --global --add safe.directory /__w/tinycoro/tinycoro

    - name: Initialize Git submodules
      run: git submodule update --init --recursive
      working-directory: ${{ github.workspace }}
    
    - name: Configure
      run: cmake -B build -D CMAKE_BUILD_TYPE=Debug -D WithASAN=ON
      working-directory: ${{ github.workspace }}

    - name: Build
      run: cmake --build build
      working-directory: ${{ github.workspace }}

    - name: Run Unit Tests
      run: ./build/test/tinycoro_tests
      working-directory: ${{ github.workspace }}

    - name: Run Examples
      run: ./build/tinycoro_example
      working-directory: ${{ github.workspace }}

    - name: Run echo server and stress test
      run: |
        ./build/example/echo_server_example/tinycoro_echo_server &
        python ./example/echo_server_example/echo_server_stress_test.py 1000 true &
        wait
      working-directory: ${{ github.workspace }}
