# Based on macos.yml from {fmt}
# https://github.com/fmtlib/fmt/blob/master/.github/workflows/macos.yml

name: macos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        compiler: [AppleClang, LLVM-Clang-16, LLVM-Clang-17, LLVM-Clang-18, LLVM-Clang-19]
        test_with: [Headers, Module]
        build_type: [Debug, Release]

        exclude:
          - compiler: AppleClang
            test_with: Module
          - compiler: LLVM-Clang-16
            test_with: Module

        include:
          - compiler: AppleClang
            cxx: clang++
            install: |
              brew install ninja
          - compiler: LLVM-Clang-16
            cxx: $(brew --prefix llvm@16)/bin/clang++
            install: |
              brew install llvm@16 ninja
          - compiler: LLVM-Clang-17
            cxx: $(brew --prefix llvm@17)/bin/clang++
            install: |
              brew install llvm@17 ninja
          - compiler: LLVM-Clang-18
            cxx: $(brew --prefix llvm@18)/bin/clang++
            install: |
              brew install llvm@18 ninja
          - compiler: LLVM-Clang-19
            cxx: $(brew --prefix llvm@19)/bin/clang++
            install: |
              brew install llvm@19 ninja
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
               $GITHUB_WORKSPACE
               
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Run Examples
      working-directory: ${{runner.workspace}}/build
      run: ./tinycoro_example
    
    - name: Run Unit Tests
      working-directory: ${{runner.workspace}}/build
      run: ./test/tinycoro_tests
