name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up MSVC environment
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    
    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress
      shell: powershell

    - name: Add safe repo directory
      run: git config --global --add safe.directory ${{ github.workspace }}

    - name: Initialize Git submodules
      run: git submodule update --init --recursive
      working-directory: ${{ github.workspace }}
    
    - name: Configure
      run: cmake -B build -D CMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64
      working-directory: ${{ github.workspace }}

    - name: Build
      run: cmake --build build --config Release
      working-directory: ${{ github.workspace }}

    - name: Run Unit Tests
      run: .\build\Release\tinycoro_tests.exe
      working-directory: ${{ github.workspace }}

    - name: Run Examples
      run: .\build\Release\tinycoro_example.exe
      working-directory: ${{ github.workspace }}
